package com.meawallet.mtp.sampleapp.enums

enum class PaymentIntentActionsEnum {
    INTENT_ACTION_PAY_BY_CHOSEN_CARD,

    INTENT_ACTION_AUTHENTICATION_REQUIRED,
    INTENT_ACTION_TRANSACTION_SUBMITTED,
    INTENT_ACTION_TRANSACTION_FAILURE,
    INTENT_ACTION_TRANSACTION_STARTED
}